workflows:
  ios-shorebird-release:
    name: iOS Shorebird Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.midnet.ecommerce.mega
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.32.8"
        APP_STORE_APPLE_ID: 1458763183 # Replace with your App Store Connect App ID
      groups:
        - app_store_credentials # Group containing SHOREBIRD_TOKEN
    scripts:
      - name: Install Shorebird CLI
        script: |
          if [ ! -d "$HOME/.shorebird" ]; then
            echo "📥 Installing Shorebird CLI..."
            curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          fi
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "PATH=$HOME/.shorebird/bin:$PATH" >> $CM_ENV
          shorebird --version

      - name: Verify shorebird.yaml
        script: |
          if [ ! -f "shorebird.yaml" ]; then
            echo "❌ shorebird.yaml not found in repo root"
            ls -la
            exit 1
          fi
            echo "✅ shorebird.yaml contents:"; cat shorebird.yaml

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: CocoaPods install
        script: |
          cd ios
          pod repo update
          pod install

      - name: Show signing identities & provisioning profiles
        script: |
          security find-identity -v -p codesigning || true
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles || true

      - name: Apply provisioning profiles (xcode-project use-profiles)
        script: |
          xcode-project use-profiles
          echo "After applying profiles:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles || true

      - name: Validate App Store provisioning profile
        script: |
          PROFILE_DIR=~/Library/MobileDevice/Provisioning\ Profiles
          EXPECTED_BUNDLE="com.midnet.ecommerce.mega"
          EXPECTED_METHOD="AppStore"
          FOUND_MATCH="false"
          if [ -d "$PROFILE_DIR" ]; then
            for p in "$PROFILE_DIR"/*.mobileprovision; do
              [ -e "$p" ] || continue
              NAME=$(grep -a -m1 "<key>Name</key>" "$p" | sed -e 's/.*<string>//' -e 's/<\/string>.*//') || true
              APPID=$(security cms -D -i "$p" 2>/dev/null | /usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin 2>/dev/null || true)
              BUNDLE=${APPID#*.}
              DIST_TYPE=$(security cms -D -i "$p" 2>/dev/null | /usr/libexec/PlistBuddy -c 'Print :ProvisionedDevices' /dev/stdin >/dev/null 2>&1 && echo "DevelopmentOrAdHoc" || echo "AppStore")
              if [ "$BUNDLE" = "$EXPECTED_BUNDLE" ] && [ "$DIST_TYPE" = "AppStore" ]; then
                echo "✅ Found App Store profile: $NAME ($p)"
                FOUND_MATCH="true"
                break
              fi
            done
          fi
          if [ "$FOUND_MATCH" != "true" ]; then
            echo "❌ No App Store provisioning profile for $EXPECTED_BUNDLE. Build will likely fail."
            echo "Please create an App Store profile in Apple Developer portal and upload to Codemagic."
          fi

      - name: Detect export_options.plist
        script: |
          FOUND=$(find /Users/builder -maxdepth 4 -name export_options.plist | head -1 || true)
          if [ -n "$FOUND" ]; then
            echo "✅ Found export options plist: $FOUND"
          else
            echo "⚠️ No export_options.plist found yet (will fallback)."
          fi

      - name: Build & Release (Shorebird)
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          EXPORT_OPTIONS=$(find /Users/builder -maxdepth 4 -name export_options.plist | head -1 || true)
          echo "Using Flutter version: $FLUTTER_VERSION"
          if [ -f "$EXPORT_OPTIONS" ]; then
            echo "Using export options plist: $EXPORT_OPTIONS"
            shorebird release ios \
              --flutter-version="$FLUTTER_VERSION" \
              --export-options-plist="$EXPORT_OPTIONS" \
              --no-confirm
          else
            echo "Fallback to --export-method=app-store"
            shorebird release ios \
              --flutter-version="$FLUTTER_VERSION" \
              --export-method=app-store \
              --no-confirm
          fi

  ios-shorebird-release-dev:
    name: iOS Shorebird Dev (No App Store Profile)
    max_build_duration: 90
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.midnet.ecommerce.mega
      vars:
        FLUTTER_VERSION: "3.32.8"
    groups:
      - app_store_credentials
    scripts:
      - name: Install Shorebird CLI
        script: |
          if [ ! -d "$HOME/.shorebird" ]; then
            curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          fi
          export PATH="$HOME/.shorebird/bin:$PATH"
      - name: Verify shorebird.yaml
        script: |
          [ -f shorebird.yaml ] || (echo "Missing shorebird.yaml" && exit 1)
      - name: Packages & Pods
        script: |
          flutter packages pub get
          cd ios && pod install
      - name: Apply profiles
        script: |
          xcode-project use-profiles
      - name: Dev build (no App Store export)
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird release ios --flutter-version "$FLUTTER_VERSION" --export-method=development --no-confirm
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Application Support/shorebird/logs/*.log
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Application Support/shorebird/logs/*.log
    
    publishing:
      email:
        recipients:
          - dev@c-castle.com # Replace with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-shorebird-release:
    name: Android Shorebird Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        FLUTTER_VERSION: "3.32.8"
        PACKAGE_NAME: "com.midnet.ecommerce.mega"
      groups:
        - app_store_credentials # Group containing SHOREBIRD_TOKEN
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install Shorebird CLI
        script: |
          if [ ! -d "$HOME/.shorebird" ]; then
            curl --proto '=https' --tlsv1.2 -sSf \
              https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          fi
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "PATH=$HOME/.shorebird/bin:$PATH" >> $CM_ENV
          shorebird --version
      
      - name: Verify shorebird.yaml
        script: |
          if [ ! -f "shorebird.yaml" ]; then
            echo "❌ shorebird.yaml not found!"
            exit 1
          fi
          echo "✅ shorebird.yaml found:"
          cat shorebird.yaml
      
      - name: Build and release with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird release android \
            --flutter-version="$FLUTTER_VERSION" \
            --artifact=aab \
            --no-confirm
    
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - $HOME/Library/Application Support/shorebird/logs/*.log
    
    publishing:
      email:
        recipients:
          - mohammed@example.com # Replace with your email
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
