workflows:
  ios-shorebird-release:
    name: iOS Shorebird Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.midnet.ecommerce.mega
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_VERSION: "3.32.8"
        APP_STORE_APPLE_ID: 1458763183 # Replace with your App Store Connect App ID
      groups:
        - app_store_credentials # Group containing SHOREBIRD_TOKEN
    scripts:
      - name: Set up local properties (Android for dependencies)
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Install Shorebird CLI
        script: |
          if [ ! -d "$HOME/.shorebird" ]; then
            curl --proto '=https' --tlsv1.2 -sSf \
              https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          fi
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "PATH=$HOME/.shorebird/bin:$PATH" >> $CM_ENV
          shorebird --version
      
      - name: Verify shorebird.yaml
        script: |
          if [ ! -f "shorebird.yaml" ]; then
            echo "❌ shorebird.yaml not found!"
            exit 1
          fi
          echo "✅ shorebird.yaml found:"
          cat shorebird.yaml
      
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Build and release with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          
          # Get the export options plist generated by xcode-project
          EXPORT_OPTIONS="/Users/builder/export_options.plist"
          
          if [ -f "$EXPORT_OPTIONS" ]; then
            echo "Using export options: $EXPORT_OPTIONS"
            shorebird release ios \
              --flutter-version="$FLUTTER_VERSION" \
              --export-options-plist="$EXPORT_OPTIONS" \
              --no-confirm
          else
            echo "⚠️  Export options not found, building without custom plist"
            shorebird release ios \
              --flutter-version="$FLUTTER_VERSION" \
              --export-method=app-store \
              --no-confirm
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Application Support/shorebird/logs/*.log
    
    publishing:
      email:
        recipients:
          - dev@c-castle.com # Replace with your email
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-shorebird-release:
    name: Android Shorebird Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        FLUTTER_VERSION: "3.32.8"
        PACKAGE_NAME: "com.midnet.ecommerce.mega"
      groups:
        - app_store_credentials # Group containing SHOREBIRD_TOKEN
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install Shorebird CLI
        script: |
          if [ ! -d "$HOME/.shorebird" ]; then
            curl --proto '=https' --tlsv1.2 -sSf \
              https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          fi
          export PATH="$HOME/.shorebird/bin:$PATH"
          echo "PATH=$HOME/.shorebird/bin:$PATH" >> $CM_ENV
          shorebird --version
      
      - name: Verify shorebird.yaml
        script: |
          if [ ! -f "shorebird.yaml" ]; then
            echo "❌ shorebird.yaml not found!"
            exit 1
          fi
          echo "✅ shorebird.yaml found:"
          cat shorebird.yaml
      
      - name: Build and release with Shorebird
        script: |
          export PATH="$HOME/.shorebird/bin:$PATH"
          shorebird release android \
            --flutter-version="$FLUTTER_VERSION" \
            --artifact=aab \
            --no-confirm
    
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/*.apk
      - $HOME/Library/Application Support/shorebird/logs/*.log
    
    publishing:
      email:
        recipients:
          - mohammed@example.com # Replace with your email
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
